### ISSUE TITLE
Barrel type and item translation option

### ISSUE THREAD

**Issue by lackooka** [BreweryTeam/BreweryRecipesAddon#6]
Hi. I want to translate the barrel type and items, but I cant do it, because it is not on the config files. Is it possible to make it translatable or use minecraft translation?

**Comment by Jsinco** [comment]
RecipesAddon uses the words written in the ingredients category of each recipe. I'd have to look into translating this in the addon via some kind of api. I'll probably end up using PikaMug's API for this when I get the free time for this: https://www.spigotmc.org/threads/1-7-2-1-19-show-translated-item-entity-etc-names-in-clients-language.363866/

This is also more of a suggestion rather than an issue, so I'm closing this for now.
